
//Show one color scheme
GET http://localhost:3000/api/color-schemes/5 HTTP/1.1

###

//Show all color scheme
GET http://localhost:3000/api/color-schemes HTTP/1.1

###

//Show Hello World
GET http://localhost:3000 HTTP/1.1

###

//Add a color scheme
POST http://localhost:3000/api/color-schemes HTTP/1.1
content-type: application/json

{
    "colorScheme": "luke",
    "hex": ["#2B886d", "#fbe894", "#fcfaf1", "#71dbd4"],
    "creatorName": "creators inc"
}

###

//Uppdate one color scheme
PUT http://localhost:3000/api/color-schemes/3 HTTP/1.1
content-type: application/json

{
    "colorScheme": "stella",
    "hex": ["#2B886d", "#fbe894", "#fcfaf1", "#71dbd4"],
    "creatorName": "creators inc"
}

###

//Delete a color scheme
DELETE http://localhost:3000/api/color-schemes/1 HTTP/1.1
content-type: application/json

###